### ISSUE TITLE
Request: Add compatibility with Filament 3

### ISSUE THREAD

**Issue by SerhiiMandrykin** [JKHarley/filament-trumbowyg#25]
Hi

It would be great to have this plugin compatible with filament 3

Do you have any plans on updating it?

**Comment by JKHarley** [comment]
Hey! 

Thanks for your interest.

I’m very close to getting this to be compatible with Filament 3. I just have an issue with persisting the data from the database to the field. 

I’m hoping to have it released by the end of this week 🙂.

**Comment by SerhiiMandrykin** [comment]
Thank you! Looking forward to the update!

**Comment by JKHarley** [comment]
Hey @SerhiiMandrykin, i've just published a branch [here](https://github.com/JKHarley/filament-trumbowyg/tree/3.x) which has Filament 3 compatibility. I still need to give it a thorough test and then i'll be getting the changes merged into master but feel free to use the published branch in the meantime. I do plan on getting a test suite added to make it much easier in the future.

**Comment by SerhiiMandrykin** [comment]
@JKHarley thank you!
