### ISSUE TITLE
In Builder\Block can't work 

### ISSUE THREAD

**Issue by oz-hjx210** [JKHarley/filament-trumbowyg#7]
In Builder\Block can't work  when I add a block   and Save is wrong Too ,no data save to database

can you fix it,thanks

**Comment by JKHarley** [comment]
Hi, I'm actively trying to get this integrated with the ability of using the block builder. There's an issue at the moment with the id's getting mismatched and duplicated stopping the field initialising. I've added a disclaimer in the readme and should hopefully have a working update in the near future.
